on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: windows-2019

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '4.8'

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Compilar la biblioteca
        run: dotnet build --configuration Release
